image:
  tag: 1.0.6
specs: eslint nuxt oxlint oxlint-tsgolint pinia pixi.js playwright prettier rolldown tailwindcss tsdown typescript vite vitest vue
cronTime: 0 */30 * * * *
discordWebhookId: "1410572127786242130"
extraObjects:
  - apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      creationTimestamp: null
      name: npm-version-notifier
      namespace: npm-version-notifier
    spec:
      encryptedData:
        discordWebhookToken: AgCan/qgffIT/IdgXdvBXeyekiNTtdYTGuGDF5KzsGW0KX2UsAwp7ndYLxswYo9KUUUZxVmxRIQOyg5UGydY/+iCcLrZ+fiqX38brf83etOkzhtZ/xxRSbdRSmz3Sh9gXg9h3yfbugDMAF0+agmlLMoyq41wcI8eJSnrrdONQ6ZVziiGyXV4N+qWdwsZFHRSdg+Zpd5VpRHzxf460M88fG/qbuXguTZnOf0DvKBZQHbc/jvO9H9eVJc5kQ5ZDWbV2WLW+m3U5S8a6OqqfJk6BGnHxTkfe+t4s9WY61dPeKftijpfIw/f+4F/tj6lZo0d/PrkGIHRP3dLDk3JNo2dajLbGBPSPZ9EGm7jz0Y0YYuQ50CK0sseW2v5Y4uDpGrfGCEEYdvefBV6EMWI6vIBxxU02JXEAynL2+KUQAnYdbYZlE5PVh1+qPHFfsyCAWnWm80bdgtnk6p+LXM03yq0/2dq24jyusbQbQX+MImjtPXndWtoYGxTgaaSdBwPTRPIWARJAeAcqmMU4wfKfdjPW81jzgqKl8WLBiBNdf7qdTHTVuRxC5Ixon7lFrns7FSXbfCCKyCl8TiNjLvpEc9f+o64aC0c0GqEfGBkTwAnJsFqWrxBz1RII8Inqnv6aNNHjq5f/8Qn0Pv4P8711LDBrBEyOgEaVT27YVenAXMFMy9pWigUMsRPobUWBoDbGx/hx3Y/yrLn72yqwaa8WPjSyuPb0njL/pIRZLajUQUMx+lDrW1GQYpZJgtmznAaMMcspqGrq6cWrj4iWtYJKxNi7AVGneV6xw==
        githubToken: AgBOzHXHuAm03FxwKZ2DVaedYPJd/lYaP35aUBBcp0/MZz3a9Ak+gBTmXdh0e0FMe3JXnZ63NZ+Imnkr+IgrtSOCdQ32KTx9fz8I2Nhil9NcFWTTQNx1TT4n2cQX1wwt7VO3SYzLC/HSgzaFdx6lKNn93KYTHv3RVBQOAyOZw/frkaIzFVh8DQ0rI+YAjPGw27SLB+/N6n2RR2aXOPTUPtw4mDUQ5BDbqqRpXvO/F+UibrJj4+zbvw4kEdkZNIiGZpE9cEQbF7+5upm8+ANa9Y8pUlUPbtOatLNsvAEIdx3MWHPh0d0vacubmkiIV6mOJcWq6Tue8yp0eMD9b+XdX4bXJHq3ymr6le9DakDmAbtDfb7AYMypL2yUs9RMyifydZ60/9KVUszKIgScrgTq0Rxe4G2khjo9ib/Cmv0D7mAnH7AoshboPXNFKSYQznz4RRaf/JaJhRNy4xDWidrloJfiyIzGRvS6YYNsEyRtHldQ+TYFqudcElxT16ANY6Ou+o5+hmJGvFvujp5KAyxg8fT6Ec0OgSD/fGpUX5McFpv+zzOvWfJa8jGrqTjQsWK37Nv4U4iWTWfRuIqanRB9q9V/nCUWGEqJSY/B0MNj7ua6ji40BzKvwh95k3JJWh7/Bd9T9Bhu/x00TE4+0xKtSUTJtcTXLo3UnmtBveauHO39y3Q32VnnNI53xSShjBqYju3r+6mXFisPahU/6n8gpmR7thnVk8pj/B5Exj5u+0sZ3WfZNFFldRZMk8VjCwPJdf0WO+WN89ETnIHonn2xqzA8c6wwZIFmaq6PczT7PVbI4uZctKOOlwVeU2gKykw=
      template:
        metadata:
          creationTimestamp: null
          name: npm-version-notifier
          namespace: npm-version-notifier
