{{- range .Values.databases }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-secret
  namespace: {{ $.Release.Namespace }}
spec:
  encryptedData:
    username: {{ .username }}
    password: {{ .password }}
  template:
    metadata:
      name: {{ $.Release.Name }}-{{ .name }}-secret
      namespace: {{ $.Release.Namespace }}
{{- end }}
