cluster:
  instances: 1

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true

databases:
  - name: authentik
    username: AgA4t4L/1n24xC8qpg2w+WmvIeVtGRmdIkX5ajTd+kROfZf1GyjT1jPdlAlmn9owVDjrBrvZNQFq/QKZBv0odf0hKsFo5WQigFjTv5SeHujfOvNrvoO+eDIHhH/ijik4urNQscdz23O5tXEga7/8oBL++k2L7FFEGzT+jEyMrNqYSNV/9p4pzwaoUBWHDDGphuGOzQK2yDQPdDePYOfMLbeHKh0MnWS67cJb1Re3JA1Xa0VOkX+teo/tZnHpD+EVaEyx4WXGIkyhGivsJyGOlf/r75/Qs0f6kBclPJh5EbbY6TpNbIFlnHc6YwcO1oFCuewC5gJ+JHFOSzvkfWcK7UgiU3TV1WewEPQNeRVOyI3iaYzSAQRJvVT5MFiV+XdIQuxC+o/Wrz6Yag6FOTkGb6YXSUIyGSeH1qVsp30bvV3czVZtJLSZG+piTDniaPRp8DtnHgVqlwKTOYuTj4MRea6yTl82Lp+yK3jcMLwNwZ+wpUR8YS+lRX0g8CLfjf6YzPywiymeTvYVEKAV06FFOd8BJv/SeHoVL0YIIvXSsADuJPQ/38x1jhejVKOgDJWQIFwnOa1s9XSFA819DMXPBE+LC6Lt1IrKRcxPTsdG5MSAph4CokLsh44ZHkfn6QRt35lqxXcna09npMv+RVg75S57T9e3cAlQ+8HyZWuKgf0VWmgx4BRI6C8XOFNqW0VpXvke7i95YtEkUHc=
    password: AgCZXllcQCFP3mUryude+D3n5ezq/O1awuYs0WRpRUX8nkiUZwHeBq494z4+RO9CYlwkov3gGyrdvaxKHxgdRkbv9j+bywLbEgEb3YUuD4P4LiX7eULIWlw+S1aTcQBDpnt5PWYeLIjuKWx0yyT0uesnBv0ai6Lr5t72TalnehtCem+EcthV0Wtxxd2PD7zfC/oLq7N2W1iu9XPvLuvVKYZpzheSam7E7G0ScY8pamIJeqUvBXOhSW9EJJANgEOcxy7HVyI9Nbo7S4Lu7tcpoW0JPWTNrAIK82LXRg64flv1OiJKb/ALebDFfKJ9dKDZqoUM0pMudij9p4paBsM/TUrfncRJW0wg4t2dBx3ur7zIe5V36y300rzeofxp9g+FVKkzsuT2INaBEOqlVO5rv7kbGC8DNkyl9XGR2SIUHXnlLPw3ywJbNSmMr8mFVhd+zlUuiWvnte6d6LJYL6a9SbgFOy2qByLDr15Kvx7b/vHnxhe4ajVtbvkjDDYzD1DZkz0nyfL0k2xL6c/+2lSvsYGrA496EK5yfWJSd43Z041ETGYzf0VHGE7/9YYIkmNvt9lCsj6TiieI6dNOpxALOXhXaBmZ4CifnBmqt0XsXFr2YZohj1yjo0LQueTLrawsQm/A+KHSbpsB99OwdpdN2nZJArNzStbtmk2jRVw+de50z+kJYt4RbBP8Jt7DVVKGXGyKeon5hVA5g1A=
