cluster:
  instances: 1

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true

databases:
  - name: authentik
    username: AgAl7OHvwF/BlBHqtKwo+X6DZzpZQPYOKq5TR85YnJloj9vUoQTndnsE6EPQboxoZcRPaagQIYpq0m4Zl/cSL3JCOkCD9LPsHT6nE+Vh5l6zsC0j62Tgr8NKRMa0SQDTq4klk4gmFONcfWp46axIuQvSuy0ZtnrR+JdttMmt83r3lNyOGstAc8oRQRN77hk6yQLi65M84i68huU7F6gmifogHUHER2yPNHLCjAlfE5yuw8pqOjQvVBE02KOg21xlJOIw+JmUAaULJ/l7eP+jgiks10CpK7COQ7cnWIbz1bOAmcfH9WtCYv+l+ItZTWxklw/IRdGJCKOFkpQOK/vZ0D78vhWQXDc8srdeFoHtT5lIl9vHnq/vgKDh89ujRIaOAnZzgpwzlaA/2Xs52YGzld6aqgiZTUnrOM8fEGV0VmMLjhKp+pMdtQyGG/oU7jBRtVnwNRsIh5F1BtUn9VjSPidfMxtwaOebYS5WXA85c6EVcRNOT6mEBLlSq7n/OUX010LFedglB5xKn3M/b2WmAsjNX3PXK8ctI6M0HnYB6ros5EgLuyjsEaBfNAmQTQgtQtMpGGCQMMUZV2Yl+sxKGwps4kDS9IWu/1ujkGrgdSrzywiDFF14+dwYR0kMKM9k6p4iL9fG/8gC9uzyiJ564oWyd+tlQSjj1ylCiMcIKLfrAWWMFBO8cr/KuA5EI/E2es0YJEMy2n+fqrc=
    password: AgAHd936IzLZielvkdbIJCEIsEyjeTJvoh1orDL4oliVxmVTa1yW+EwAV62efQ1ByrLl6TtfnuiCiaJSMLcUPKoUJn3H2HJRJpZOJC/YCB4633NN+iO/trRqpLXOt777OPQOb1wYAciv3nvdGBmI/Lhc6BM/KwBFJNSGq3sWfn9pFjVO+iS2PppRI61kOZI7Hu1wFgLqEcYajMY8egTFQju7yy2OnFwqznVkhlMCpC4IV4s8VDh3KooC4sWBX2NyBs6LCyvlRteRXL7AdJ0HX1zbjO7JxKjL72xy7Ps8TMp2mtuu13hOTy1yVvcpzD1pdmlS2LL28GJ3FcnkEp3qI1X1BNTOHBjFEIe71A4Mh9MjPKpohomKBlN3uQJaNTqp99GVvtzWn7yfK73jFHqZds8B/mI16vC9OUYnUTPJq+RnY6q2h1WR57RJVSmJYWuN7jg10ZWpnl+mth1gqORpJ/o4Pn275ez/aPC9evkzX7rN6Z0dsJ4juoWZ2KSC7NegK/0l5bqTjbM4pB4o1J3EVHvsOzqpn5I9taHLte6G6dD7VtCKvfsd19/s9sloLKSH1IZIR/uhJatT2szUWiL2Jf32BeG5ycr/KwDiZV3+QHM8zyXQRtfW6D02O1UaT2bAwdKRJpRHsoxFQ9YM6avwxInqjs2kruCMIfOLaNdk8467TcSmK4mQGT4MkE3SRTY1UhhF6dvVNC4LsMU=
