#!/usr/bin/env bash

sxhkd &

eww daemon &
eww open bar &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          1
bspc config window_gap            0
bspc config normal_border_color   "#000000"
bspc config focused_border_color  "#008000"
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
