apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  namespace: postgresql
spec:
  instances: 1

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true

  managed:
    roles:
      - name: authentik
        login: true
