apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: npm-version-notifier
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Derviloper/dotfiles.git
    targetRevision: HEAD
    path: kubernetes/npm-version-notifier

  destination:
    server: "https://kubernetes.default.svc"
    namespace: npm-version-notifier

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
