apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 37.0.0
      helm:
        valuesFiles:
          - $values/values.yaml
    - repoURL: https://github.com/Derviloper/dotfiles.git
      targetRevision: HEAD
      path: kubernetes/traefik
      ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
